### ISSUE TITLE
Demo instance at GitHub Pages

### ISSUE THREAD

**Issue by sio** [albertprz/puresheet#2]
How about providing a demo instance hosted at GitHub pages? It's free and relatively straightforward to setup.

Initially I wanted to provide this suggestion along with a PR but I could not build the app, unfortunately. Here is [an example](https://github.com/sio/advent-of-code/blob/38379a04414ab297d628b36439bc3b951a37d5d1/.github/workflows/aoc2023.yml#L31-L37) of me deploying a basic Halogen app to GitHub Pages. You will also need to change some repository settings:

![GitHub Pages settings](https://github.com/albertprz/puresheet/assets/334908/17d146bf-b4b1-4b4a-a71f-e9bf4a8098c1)

I'm willing to help with GitHub pages setup if you'll help me to figure out how to build this app correctly. My build (following the README) resulted in a [broken spreadsheet UI](https://github.com/albertprz/puresheet/assets/334908/c9ea20ba-9d94-453b-8c6d-4d6cb52cc0e1) (only the first cell is rendered; keyboard navigation works in a "blind mode").

**Comment by albertprz** [comment]
Hi @sio. Apologies for the late response and thanks for both the suggestion and the offer to help with the Pages setup.

I have just recently deployed the latest version, so it is now finally available as a demo.

I've had some struggles trying to keep the standard library as standalone files, which worked via Parcel bundle inlining for local deployments, but not for a bundle, so I decided to keep the standard library modules embeded in Purescript  files as a temporary solution.
